version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: juice-vault-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP HTTP
      - "4317:4317"    # OTLP gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - juice-vault-network

networks:
  juice-vault-network:
    driver: bridge